Mesocycle_Maker/Models/Category.cs
namespace Mesocycle_Maker.Models
{
    public class Category
    {
        public Category()
        {

        }

        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}

Mesocycle_Maker/Models/ErrorViewModel.cs
namespace Mesocycle_Maker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mesocycle_Maker/Models/Exercise.cs
namespace Mesocycle_Maker.Models
{
    public class Exercise
    {
        public Exercise()
        {

        }

        public int ExerciseID { get; set; }
        public string ExerciseName { get; set; }
        public int CategoryID { get; set; }
    }
}

Mesocycle_Maker/Models/ExercisePerMeso.cs
namespace Mesocycle_Maker.Models
{
    public class ExercisePerMeso
    {
        public ExercisePerMeso()
        {

        }

        public int UserMesoID { get; set; }
        public int ExerciseID { get; set; }
        public int ExerciseTenRPM { get; set; }
        public string ExerciseOnDay { get; set; }
        public string ExerciseName { get; set; }

    }
}

Mesocycle_Maker/Models/User.cs
namespace Mesocycle_Maker.Models
{
    public class User
    {
        public User()
        {

        }

        public int UserMesoID { get; set; }
        public string UserMesoGoal { get; set; }
        public int UserMesoWeekLength { get; set; }
    }
}

Mesocycle_Maker/Models/UserMeso.cs
namespace Mesocycle_Maker.Models
{
    public class UserMeso
    {
        public UserMeso()
        {

        }

        public int UserMesoID { get; set; }
        public string UserMesoGoal { get; set; }
        public int UserMesoWeekLength { get; set; }
    }
}

Mesocycle_Maker/Controllers/ExercisePerMesoController.cs
using Mesocycle_Maker.Models;
using Microsoft.AspNetCore.Mvc;

namespace Mesocycle_Maker.Controllers
{
    public class ExercisePerMesoController : Controller
    {
        private readonly IExercisePerMesoRepo repo;

        public ExercisePerMesoController(IExercisePerMesoRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var ePM = repo.GetAll(); 
            return View(ePM);
        }

        public IActionResult Results(int userMesoID)
        {
            var exPM = repo.GetOneWithNames(userMesoID);
            return View("Results", exPM);
        }
    }
}

Mesocycle_Maker/Controllers/HomeController.cs
using Mesocycle_Maker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Mesocycle_Maker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mesocycle_Maker/Controllers/UserMesoController.cs
using Microsoft.AspNetCore.Mvc;
using Mesocycle_Maker.Models;

namespace Mesocycle_Maker.Controllers
{
    public class UserMesoController : Controller
    {
        private readonly IUserMesoRepo repo;

        public UserMesoController(IUserMesoRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult NewUserMeso(User user)
        {
            repo.InsertUserMeso(user.UserMesoGoal, user.UserMesoWeekLength);
            var newUser = repo.GetOneWithoutID(user.UserMesoGoal, user.UserMesoWeekLength);
            return View("NewUserMeso", newUser);
        }
    }
}

Mesocycle_Maker/Views/ExercisePerMeso/Index.cshtml
@model IEnumerable<ExercisePerMeso>

    <h2> Exercises Per User Mesocycle ID </h2>
        <table class="table">
            <tr>
                <th>User Meso ID</th>
                <th>Exercise ID</th>
                <th>Ten Rep Max</th>
                <th>Day Of Exercise</th>
            </tr>

            @foreach (var ex in @Model)
            {
                <tr>
                    <td>@ex.UserMesoID</td>
                    <td>@ex.ExerciseID</td>
                    <td>@ex.ExerciseTenRPM</td>
                    <td>@ex.ExerciseOnDay</td>
                </tr>
            }
        </table>

Mesocycle_Maker/Views/ExercisePerMeso/Results.cshtml
@model IEnumerable<Mesocycle_Maker.Models.ExercisePerMeso>

<p>
    <a asp-action="Create">Create New Mesocycle</a>
</p>


<h2>Results</h2>
<table class="table" id="sortTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExerciseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExerciseTenRPM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExerciseOnDay)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExerciseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExerciseTenRPM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExerciseOnDay)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Mesocycle_Maker/Views/Home/Index.cshtml
@model User

<div class="text-center">
    <h1 class="display-4">Mesocycle Maker</h1>
</div>

<div>
    <h5>Enter your Mesocycle ID</h5>
</div>


<!--To pull up a user mesocycle-->
<div>
    <div>
        <form asp-controller="ExercisePerMeso" asp-action="Results">

            <div class="mb-3">

                <label asp-for="UserMesoID" class="control-label">Mesocycle ID</label>
                <input asp-for="UserMesoID" class="form-control" min=1 max=9999 maxlength=4/>
                <span asp-validation-for="UserMesoID" class="text-danger"></span>
            </div>
           
            <button type="submit" class="btn btn-primary">Submit</button>
           
            
        </form>
    </div>
</div>




<!--To create a new user mesocycle-->
<h2>Create a new mesocycle</h2>
<p>Enter the information below to create a new mesocycle.</p>
<div>
    <div class="container"
        <form asp-controller="UserMeso" asp-action="NewUserMeso">
            <div class="row">
                <div class="col">
                    <label asp-for="UserMesoGoal" class="form-label">Mesocycle Goal</label>
                    <input asp-for="UserMesoGoal" class="form-control" id="UserMesoGoal" aria-describedby="mesoGoalHelp" placeholder="A short description about your goals for this mesocycle." />
                </div>
                <div class="col-md-4">
                    <label asp-for="UserMesoWeekLength" class="form-label">Number of weeks for mesocycle</label>
                    <input asp-for="UserMesoWeekLength" class="form-control" id="UserMesoWeekLength" min=4 max=12 placeholder="For best results, 4(min)-12(max)." />
                </div>

                <div class="mb-3">
                        <button type ="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

Mesocycle_Maker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mesocycle_Maker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mesocycle_Maker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mesocycle_Maker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExercisePerMeso" asp-action="Index">Mesocycle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Mesocycle_Maker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mesocycle_Maker/Views/UserMeso/NewUserMeso.cshtml
@model IEnumerable<UserMeso>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserMesoID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserMesoGoal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserMesoWeekLength)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in @Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserMesoID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserMesoGoal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserMesoWeekLength)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>